- src/client/app/components/App.jsx
- src/client/app/components/ConsoleOutput.jsx
- src/client/app/components/EditorContainer.jsx
- src/client/app/components/JavascriptOutput.jsx
- src/client/app/components/P5Editor.jsx
- src/client/app/components/P5Output.jsx
- src/client/public/hijackConsole.js
Add a console component to the output
> Add console

- src/client/app/components/App.jsx
- src/client/app/components/ConsoleOutput.jsx
- src/client/app/components/EditorContainer.jsx
- src/client/app/components/P5Editor.jsx
- src/client/app/components/PythonEditor.jsx
- src/client/app/components/PythonOutput.jsx
- src/client/app/components/TextEditor.jsx
Move state of editor to the main App file
> editors are of global state

- .gitignore
- src/client/public/hijackConsole.js
make sure that the hijackConsole file is not included in gitignore
> Fix console

- .eslintrc
- src/client/app/components/App.jsx
- src/client/app/components/ConsoleOutput.jsx
- src/client/app/components/EditorContainer.jsx
- src/client/app/components/EditorToolbar.jsx
- src/client/app/components/Iframe.jsx
- src/client/app/components/InsertToolbar.jsx
- src/client/app/components/JavascriptEditor.jsx
- src/client/app/components/JavascriptOutput.jsx
- src/client/app/components/Login.jsx
- src/client/app/components/MainToolbar.jsx
- src/client/app/components/Modal.jsx
- src/client/app/components/P5Editor.jsx
- src/client/app/components/P5Output.jsx
- src/client/app/components/PagesList.jsx
- src/client/app/components/SignUp.jsx
- src/client/app/components/TextEditor.jsx
- src/client/app/components/TextToolbar.jsx
- src/server/server.jsx
> re-enforce prop-types

- src/client/app/components/Login.jsx
- src/client/app/components/SignUp.jsx
> Hide password while typing

- src/client/app/action/mainToolbar.jsx
- src/client/app/reducers/editorContainer.jsx
- src/client/app/reducers/iframe.jsx
- src/client/app/reducers/textEditors.jsx
> add min size for elements

- src/client/app/action/user.jsx
- src/client/app/components/App.jsx
- src/client/app/components/JavascriptEditor.jsx
- src/client/app/components/Login.jsx
- src/client/app/components/MainToolbar.jsx
- src/client/app/components/Modal.jsx
- src/client/app/components/SignUp.jsx
- src/client/app/components/TextEditor.jsx
- src/client/app/constants.jsx
- src/client/app/reducers/editorContainer.jsx
- src/client/app/reducers/user.jsx
- src/server/controllers/apiController.js
> Add ability to fork and save

- src/client/app/action/mainToolbar.jsx
- src/client/app/components/MainToolbar.jsx
- src/client/app/reducers/mainToolbar.jsx
- src/server/controllers/pageController.js
- src/server/models/page.js
> add parent id to forked page

- src/client/app/action/mainToolbar.jsx
- src/client/app/components/App.jsx
- src/client/app/components/MainToolbar.jsx
- src/client/app/components/PagesList.jsx
- src/client/app/index.jsx
> change URL to pebl

- src/client/app/action/mainToolbar.jsx
- src/client/app/components/App.jsx
- src/client/app/components/JavascriptEditor.jsx
- src/client/app/components/PagesList.jsx
- src/client/app/constants.jsx
- src/client/app/reducers/mainToolbar.jsx
- src/server/controllers/pageController.js
> add ability to delete pages

- src/client/app/components/MainToolbar.jsx
- src/client/app/styles/sass/mainToolbar.scss
> add link to make new page

- src/client/app/action/page.jsx
- src/server/controllers/pageController.js
> redirect user on delete

- src/client/app/components/Canvas.jsx
- src/client/app/styles/sass/textEditor.scss
> remove text focus

- src/client/app/components/Canvas.jsx
- src/client/app/styles/sass/textEditor.scss
> Revert "remove text focus"

- src/client/app/components/P5Output.jsx
> remove event listener on unmount

- src/client/app/action/editorContainer.jsx
- src/client/app/action/iframe.jsx
- src/client/app/action/page.jsx
- src/client/app/action/textEditors.jsx
- src/client/app/components/App.jsx
- src/client/app/components/Canvas.jsx
- src/client/app/components/EditorContainer.jsx
- src/client/app/components/Iframe.jsx
- src/client/app/components/InsertToolbar.jsx
- src/client/app/components/MainToolbar.jsx
- src/client/app/components/TextEditor.jsx
> dispatch setUnsavedChanges from respective actions

- src/client/app/components/App.jsx
- src/client/app/components/SignUp.jsx
- src/client/app/styles/sass/main.scss
- src/client/app/styles/sass/signup.scss
> Style signup page

- src/client/app/components/TextEditor.jsx
- src/client/app/styles/sass/textEditor.scss
> remove extra features in text editor

- src/client/app/components/MainToolbar.jsx
> change fork and save language

- src/client/app/components/Canvas.jsx
- src/client/app/reducers/page.jsx
fixes #190 and #194 
I reduced the height change as minimum as possible, doesn't look as fluid as the width though. what do you think @estherhersh
> change row height

- src/client/app/reducers/page.jsx
> add default title

- package-lock.json
- package.json
- src/client/app/components/Iframe.jsx
This is to fix #107 
Users can now put in a URL or an embed link from youtube/vimeo.
I.e - we can put in 
`<iframe width="560" height="315" src="https://www.youtube.com/embed/AaGK-fj-BAM" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>`
or
`https://www.youtube.com/embed/KkyIDI6rQJI`
> parse iframe url

- package-lock.json
- src/client/app/components/App.jsx
- src/client/app/components/ShareModal.jsx
- src/client/app/styles/sass/modals.scss
- src/client/app/styles/sass/shareModal.scss
- src/client/app/styles/sass/variables.scss
- src/client/index.html
> add google classroom share button

- src/client/app/components/Modals/Login.jsx
- src/server/config/passport.js
> add ability to sign in with email

- ISSUE_TEMPLATE.md
- README.md
> add readme and issue template

- PULL_REQUEST_TEMPLATE.md
> add PR template

- client/src/app/components/App/App.jsx
> fix  helphero

- client/src/app/components/App/App.jsx
- client/src/app/components/App/Modal/ExamplesModal/ExamplesModal.jsx
- client/src/app/components/App/Modal/ExamplesModal/examplesModal.scss
- client/src/app/components/App/Modal/PagesList/pagesList.scss
> Restyle examples modal

- client/src/app/components/App/Canvas/Iframe/Iframe.jsx
> #465 : Confirm if element is indeed iframe

- client/src/app/components/App/MainToolbar/MainToolbar.jsx
> #489: redirect peblio logo

- client/src/app/components/App/Modal/PagesList/pagesList.scss
> #438 : change bg color to yellow

- client/src/app/components/App/Canvas/Image/Image.jsx
> make width 100%

- client/package.json
- client/src/app/components/App/Canvas/WidgetNav/WidgetNav.jsx
- client/src/app/components/App/MainToolbar/MainToolbar.jsx
- client/src/app/components/App/Navigation/Navigation.jsx
- client/src/app/components/App/Shared/EditorComponents/ConsoleOutput/ConsoleOutput.jsx
- client/src/app/components/App/Shared/EditorComponents/EditorToolbar/EditorToolbar.jsx
- client/src/app/components/App/Shared/EditorComponents/EditorToolbar/editorToolbar.scss
- client/src/app/styles/sass/base.scss
- server/controllers/pageController.js
> Remove tooltip

- client/src/app/components/App/Modal/ShareWorkspace/ShareWorkspace.jsx
fixes #526 
This PR adds a parent Id when workspaces are shared. These parentIds are prefaced with 'src-'
Thank you!
> #526 : add parent id for sharing in workspace

- server/package-lock.json
- server/run_with_credstash.sh
- server/server.js
> #532 : move session secret to credstash

- client/src/app/components/App/Modal/SignUp/SignUp.jsx
- server/userConstants.js
fixes #309 
This PR does the following - 
* Clean up the language of the warnings when logging in/signing up
* Make the sign up form disappear on hitting submit
* Clean  up the  functions within the component
Thank you!
> #309 : Sign up clean up

- client/src/app/constants/widgetConstants.js
- client/src/app/reducers/editors.js
> #281 : Editor constants

- client/src/app/components/App/App.jsx
- client/src/app/components/App/Canvas/canvas.scss
- client/src/app/components/App/MainToolbar/mainToolbar.scss
- client/src/app/components/App/app.scss
fixes #193 
This PR removes the responsiveness on the toolbar
If the screen becomes smaller, the toolbar just scrolls on the x direction
Thank you!
> #193 : remove responsiveness of toolbar

- .gitignore
- .vscode/launch.json
- .vscode/tasks.json
- developer_docs/README.md
- server/export_creds.sh
> Debug server setup

- client/src/app/components/App/Shared/EditorComponents/CodeOutput/FrontEndOutput.jsx
> Revert "Anchor link"

- client/src/app/components/App/Shared/EditorComponents/CodeOutput/FrontEndOutput.jsx
> Check if href exists before matching

- client/src/app/components/App/App.jsx
- client/src/app/components/App/MainToolbar/MainToolbar.jsx
- client/src/app/reducers/editors.js
- client/src/app/reducers/folders.js
- client/src/app/reducers/mainToolbar.js
- client/src/app/reducers/navigation.js
- client/src/app/reducers/page.js
- client/src/app/reducers/workspace.js
> logout of a page and redirect

- client/src/app/components/App/Canvas/Canvas.jsx
- tests/canvas/tags-test.js
> display tag input in Canvas

- client/src/app/components/App/Canvas/Tags/Tags.jsx
> add trim to tags

- client/src/app/action/page.js
> Capture snapshot with fixed width and height

- client/src/app/components/App/Modal/ShareWorkspace/ShareWorkspace.jsx
> workspace-err

- client/src/app/components/App/Canvas/Image/Image.jsx
> #615 fix typos on image crop

- server/package-lock.json
- server/package.json
> add mquery

- client/src/app/components/App/App.jsx
- client/src/app/index.jsx
> force reload page on navigation

- client/src/app/components/App/Canvas/Tags/Tags.jsx
> fix peblio studio link

- client/src/app/components/App/App.jsx
- client/src/app/components/App/MainToolbar/MainToolbar.jsx
- client/src/app/reducers/page.js
> Replace page

- client/src/app/components/App/Canvas/Tags/Tags.jsx
fixes #629 
fixes #626
Thank you!
> add tag input handlers

- client/src/app/components/App/App.jsx
- client/src/app/components/App/MainToolbar/MainToolbar.jsx
> Revert "Replace page"

- client/src/app/components/App/Canvas/Canvas.jsx
- client/src/app/components/App/Canvas/Iframe/Iframe.jsx
- client/src/app/components/App/Canvas/canvas.scss
- tests/canvas/iframe-test.js
> Render Videos only when they are in frame

- client/src/app/action/page.js
- client/src/app/components/App/Canvas/Tags/Tags.jsx
- server/scripts/export_creds.sh
- server/scripts/run_with_credstash.sh
- server/src/controllers/apiController.js
- server/src/service/pageService.js
- server/test/controllers/examplesControllerTest.js
- server/test/service/logServiceTest.js
- server/test/service/pageServiceTest.js
- server/test/service/tagServiceTest.js
- server/test/service/userRegisterActionsServiceTest.js
- server/test/service/userServiceTest.js
- server/test/utils.js
> Unit test refactoring

- developer_docs/README.md
- server/scripts/export_creds.sh
- server/scripts/run_with_credstash.sh
- server/src/controllers/apiController.js
- server/src/service/pageService.js
> Use peblio AWS profile instead of default

- server/src/controllers/apiController.js
- server/src/routes/apiRoutes.js
- server/src/server.js
- server/test/controllers/apiControllerTest.js
> Return 404 when user not sound while retrieving sketches

- client/src/app/components/App/Canvas/TextEditor/textEditor.scss
> #505 : force h1 and h2 styles

- client/src/app/components/App/App.jsx
- client/src/app/components/App/Canvas/Canvas.jsx
- client/src/app/components/App/Canvas/Iframe/Iframe.jsx
- client/src/app/components/App/Modal/AddDescription/AddDescription.jsx
> #627 : fix lint errors

- client/src/app/components/App/Canvas/TextEditor/textEditor.scss
> #182 : force align all text

- client/src/app/components/App/Canvas/TextEditor/textEditor.scss
> enforce only font size and line height in text boxes

- server/src/models/user.js
- server/src/service/pageService.js
- server/test/service/pageServiceTest.js
> Remove pages from user

- client/package-lock.json
- client/package.json
- client/src/app/components/App/Canvas/EditorContainer/editorContainer.scss
- client/src/app/components/App/Canvas/WidgetNav/WidgetNav.jsx
- client/src/app/components/App/MainToolbar/MainToolbar.jsx
- client/src/app/components/App/MainToolbar/mainToolbar.scss
- client/src/app/components/App/Navigation/Navigation.jsx
- client/src/app/components/App/Shared/EditorComponents/ConsoleOutput/ConsoleOutput.jsx
- client/src/app/components/App/Shared/EditorComponents/ConsoleOutput/consoleOutput.scss
- client/src/app/components/App/Shared/EditorComponents/EditorToolbar/EditorToolbar.jsx
- client/src/app/components/App/Shared/EditorComponents/EditorToolbar/editorToolbar.scss
- client/src/app/styles/sass/base.scss
fixes #484 
This PR is WIP
It adds rollover text to the below elements when you hover on them - 
**Table of contents:**
1. Refresh
1. Close
**Components:**
1. Duplicate
1. Drag and Drop
1. Delete
**Main Toolbar:**
1. Settings
1. Account
**Editor:**
1. Run Code
1. Stop Code
1. Toggle Console
Yet to add rollover text to the below 
**Closed Table of contents icon:**
1. Table of contents
**Main Toolbar:**
1. Page Title
Thank you!
> #484 : add rollover text - WIP

- client/package-lock.json
- server/package-lock.json
- server/package.json
> Fix security alert for serve

- client/src/app/action/folders.js
- client/src/app/components/App/Modal/PagesList/FolderContainer/FolderContainer.jsx
- client/src/app/components/Profile/Pebls/ProfileLevel/ProfileLevel.jsx
- server/src/controllers/apiController.js
- server/test/controllers/apiControllerTest.js
> Sort pages by provided option or default sort by updatedAt

- client/src/app/index.jsx
- tests/mainToolBar/file-menu-test.js
> add default path to switch routes

- client/package.json
- client/src/app/action/page.js
- client/src/app/components/App/App.jsx
- client/src/app/components/App/MainToolbar/MainToolbar.jsx
> Save Page snapshot only when page explicitly saved or newly created

- server/src/service/pageService.js
- server/test/service/pageServiceTest.js
> Check user on delete

- client/src/app/components/App/Modal/PagesList/FolderContainer/FolderContainer.jsx
- tests/mainToolBar/file-menu-test.js
> #686 : sort files by timestamp

- client/src/app/action/page.js
- client/src/app/components/App/App.jsx
- client/src/app/components/App/Canvas/Canvas.jsx
This PR ensures that we do not call `setUnsavedChanges` on  `
Thank you!
> Set unsaved page fix

- .vscode/launch.json
- server/src/controllers/pageController.js
- server/src/routes/pageRoutes.js
- server/src/service/pageService.js
- server/test/controllers/pageControllerTest.js
- server/test/service/pageServiceTest.js
> Add api to retrieve my pages with tags

- client/src/app/action/folders.js
- client/src/app/action/page.js
- client/src/app/components/Shared/Documents/DocumentsView/Pages/Page.jsx
- client/src/app/constants/pageConstants.js
> add default snapshot image if there is no image

- client/src/app/components/Shared/Documents/DocumentsView/Pages/Page.jsx
> Copy snapshot path when deplicating page from dashboard

- client/src/index.html
> add google tag manager

- server/src/service/pageService.js
- server/test/service/pageServiceTest.js
> Return 404 for page that are trashed or deleted when trying to retrieve

- requirements.txt
> Upgrade ansible to 2.6.14 due to security alert

- client/src/app/action/folders.js
- client/src/app/components/App/Canvas/Canvas.jsx
- client/src/app/components/App/Canvas/EditorContainer/editorContainer.scss
- client/src/app/components/App/Canvas/EditorContainer/resizer.scss
- client/src/app/components/App/Canvas/TextEditor/textEditor.scss
- client/src/app/components/App/Canvas/WidgetNav/widgetNav.scss
- client/src/app/components/App/MainToolbar/InsertToolbar/insertToolbar.scss
- client/src/app/components/App/MainToolbar/mainToolbar.scss
- client/src/app/components/App/Modal/Login/Login.jsx
- client/src/app/components/App/Modal/Login/login.scss
- client/src/app/components/App/Shared/EditorComponents/EditorToolbar/EditorToolbar.jsx
- client/src/app/components/App/Shared/EditorComponents/EditorToolbar/editorToolbar.scss
- client/src/app/components/Dashboard/Account/account.scss
- client/src/app/components/Dashboard/dashboard.scss
- client/src/app/components/Profile/profile.scss
- client/src/app/components/Shared/Documents/DocumentsView/Pages/Pages.jsx
- client/src/app/components/Shared/Documents/DocumentsView/Pages/pages.scss
- client/src/app/components/Shared/Documents/documents.scss
- client/src/app/components/Shared/Nav/Nav.jsx
- client/src/app/components/Shared/Nav/nav.scss
- client/src/app/components/Shared/UserAccount/userAccount.scss
- client/src/app/reducers/dashboard.js
- client/src/app/styles/sass/modal.scss
- client/src/app/styles/sass/variables.scss
PR fixes #736 
[Issue list](https://github.com/peblio/app/issues/736)
Thank you!
> fix design issues listed in #736

- client/src/app/components/App/MainToolbar/MainToolbar.jsx
- client/src/app/components/Shared/UserAccount/UserAccount.jsx
- client/src/app/styles/sass/base.scss
> add identifiers for google tm

- client/src/index.html
peblio is taking time to load because it is searching for the mouseflow cdn. We are not using this application anymore, so this PR is commenting out the mouseflow CDN
Thank you!
> remove mouseflow

- client/src/app/action/folders.js
- client/src/app/components/Dashboard/Account/account.scss
- client/src/app/components/Profile/Profile.jsx
- client/src/app/components/Profile/profile.scss
- client/src/app/components/Shared/Documents/DocumentsView/BreadCrumbs/BreadCrumb.jsx
- client/src/app/components/Shared/Documents/DocumentsView/BreadCrumbs/BreadCrumbs.jsx
- client/src/app/components/Shared/Documents/DocumentsView/DocumentsView.jsx
- client/src/app/components/Shared/Nav/Nav.jsx
- client/src/app/reducers/dashboard.js
- client/src/app/reducers/folders.js
This PR does the following - 
* Ensures that the default sort for dashboard is by title
* Fix breadcrumbs in profile - they now work - fixes #743 
Thank you!
> ensure profile breadcrumbs work

- client/src/app/components/App/Canvas/TextEditor/textEditor.scss
- client/src/app/components/App/MainToolbar/mainToolbar.scss
- client/src/app/components/App/Shared/EditorComponents/EditorToolbar/editorToolbar.scss
- client/src/app/images/video.svg
> 679 design qa

- client/src/app/components/App/MainToolbar/MainToolbar.jsx
> remove saveSnapshot on page unload

- client/src/app/components/App/Shared/EditorComponents/ConsoleOutput/ConsoleOutput.jsx
> Console issue - fix scroll to output in console

- client/src/app/components/Shared/Documents/DocumentsView/Folders/Folder.jsx
- client/src/app/reducers/folders.js
- server/src/controllers/apiController.js
- server/src/models/folder.js
Getting files and folders if user has over 100 was getting very slow.
So in this PR -
1. Removed the virtual files that are linkde to folders
2. did not return Page data -> editors, layouts, workspace
Thank you!
> remove virtual files from folder

- client/src/app/action/navigation.js
- client/src/app/components/App/App.jsx
> leftover comments from history-of-pages

- client/src/app/action/page.js
- client/src/app/action/pageVersion.js
> change loadEditors to loadWidgets

- client/webpack.config.js
> Split main file to chunks to enable parallel downloads

- client/package.json
> fix history version

- client/src/app/components/App/App.jsx
> Remove fetchAllPages call from App.jsx. This is not required

- client/src/app/components/Profile/profile.scss
> fix profile background

- client/src/app/components/App/Canvas/EditorContainer/editorContainer.scss
> decrease workspace height

- client/src/app/constants/codeConstants.js
- server/integrationTest/fixtures/pageSaveFixture.json
- server/integrationTest/fixtures/pageVersion1SaveFixture.json
- server/integrationTest/fixtures/pageVersion2SaveFixture.json
> upgrade p5 to 0.9.0

- client/src/app/components/App/App.jsx
> set preview mode

- client/src/app/components/App/Shared/EditorComponents/ConsoleOutput/ConsoleOutput.jsx
> fix scroll

- .vscode/launch.json
- .vscode/tasks.json
- server/integrationTest/pageHistoryJourneyTest.js
- server/integrationTest/userFolderSizeJourneyTest.js
- server/package.json
- server/src/controllers/apiController.js
- server/src/routes/apiRoutes.js
- server/test/controllers/apiControllerTest.js
> File size check before upload

- client/src/app/components/App/App.jsx
> Comment the socket send message after page has been updated

- client/src/app/components/App/Shared/EditorComponents/CodeOutput/FrontEndOutput.jsx
- client/src/app/components/App/Shared/EditorComponents/EditorFiles/EditorFiles.jsx
- client/src/app/components/App/Shared/EditorComponents/EditorOpenFiles/EditorOpenFiles.jsx
- client/src/app/components/App/Shared/FileUpload/FileUpload.jsx
- client/src/app/constants/widgetConstants.js
This PR fixes #788 
And adds ability to add mp3, wav files for audio
and ttf and otf for fonts
Thank you!
> add support for mp3, wav, otf and ttf

- client/src/app/components/App/Canvas/Image/image.scss
> Fix #759 : fix upload image css for small images

- client/src/app/components/App/Shared/EditorComponents/EditorFiles/EditorFile.jsx
- client/src/app/components/App/Shared/EditorComponents/EditorToolbar/EditorToolbar.jsx
- client/test/app/components/App/Shared/EditorComponents/EditorFiles/EditorFile-test.js
> Fix #777 : File delete

- client/src/app/components/App/Modal/PagesList/pagesList.scss
- client/src/app/components/App/Shared/EditorComponents/EditorFiles/EditorFile.jsx
- client/src/app/components/Dashboard/Dashboard.jsx
- client/src/app/components/Dashboard/dashboard.scss
- client/src/app/components/Profile/Profile.jsx
- client/src/app/components/Shared/Documents/DocumentsView/Pages/pages.scss
- client/src/app/components/Shared/Nav/Nav.jsx
- client/src/app/components/Shared/Nav/SideNav.jsx
- client/src/app/components/Shared/Nav/nav.scss
- client/src/app/styles/sass/variables.scss
- server/package-lock.json
> Fixes #784 : Account redesign

- client/package-lock.json
- client/package.json
- client/src/app/components/Payment/CheckoutForm.jsx
- client/src/app/components/Payment/PaymentPage.jsx
- client/src/app/index.jsx
- client/test/app/components/Payment/CheckoutForm-test.js
- client/test/app/components/Payment/PaymentPage-test.js
> Stripe payment mg

- client/src/app/components/App/Canvas/canvas.scss
- client/src/app/components/App/Navigation/Navigation.jsx
> Close navigation content in mobile view

- client/src/app/components/App/Canvas/canvas.scss
- client/src/app/components/App/Navigation/Navigation.jsx
> Revert "Close navigation content in mobile view"

- client/src/app/action/page.js
- client/src/index.html
> Show alert when leaving unsaved page

- server/package.json
- server/src/controllers/apiController.js
- server/src/routes/apiRoutes.js
- server/test/controllers/apiControllerTest.js
> add api for newsletter

- client/src/app/components/Shared/Nav/Nav.jsx
- client/src/app/components/Shared/Nav/SideNav.jsx
> remove duplicate storage message

- client/src/app/components/App/Workspace/Workspace.jsx
- tests/workspace/workspace-test.js
> add editor files to workspace

- client/src/app/components/App/Shared/EditorComponents/EditorViews/SplitEditorContainer.jsx
- client/src/app/reducers/editors.js
@komalahuwalia  - could you please fill in the below?
Thank you!
> Fix editor width resize issue

- client/src/app/components/App/Modal/SignUp/PeblioSignUpForm.jsx
- client/src/app/components/App/Modal/SignUp/SignUpOption.jsx
- client/src/app/components/App/Shared/GoogleButton/GoogleSignupButton.jsx
- server/src/controllers/authController.js
- tests/auth/studnet-signup-autologin-test.js
> 816 autologin student

- .vscode/settings.json
- client/src/app/components/App/Canvas/EditorContainer/EditorContainer.jsx
- client/src/app/components/App/Modal/PagesList/FolderContainer/FolderContainer.jsx
- client/src/app/components/App/Modal/PagesList/FolderRow/FolderRow.jsx
- client/src/app/components/App/Modal/PagesList/PageRow/PageRow.jsx
- client/src/app/components/App/Shared/EditorComponents/ConsoleOutput/ConsoleOutput.jsx
- client/src/app/components/App/Workspace/Workspace.jsx
- client/src/app/components/Payment/CheckoutForm.jsx
- client/src/app/components/Shared/Documents/DocumentsView/BreadCrumbs/BreadCrumb.jsx
- client/src/app/components/Shared/Documents/DocumentsView/DocumentsView.jsx
- client/src/app/components/Shared/Documents/DocumentsView/Folders/Folder.jsx
- client/src/app/components/Shared/Documents/DocumentsView/Pages/Page.jsx
- client/src/app/constants/welcomeConstants.js
> Fix eslint

- client/src/app/components/App/Canvas/Tags/Tags.jsx
> check if tag inout is present

- server/src/service/pageService.js
- server/test/service/pageServiceTest.js
> Send page Number instead of offset for loading pebls matching tags

- client/src/app/action/page.js
- client/src/app/components/App/App.jsx
- client/src/app/components/App/MainToolbar/MainToolbar.jsx
- client/src/index.html
> Remix unsaved changes bug

- client/src/app/components/App/App.jsx
- client/src/app/components/App/MainToolbar/MainToolbar.jsx
- tests/mainToolBar/main-toolbar-test.js
> Show page title in HTML Document title

- client/.storybook/main.js
- client/package.json
- client/src/components/button/button.stories.js
- developer_docs/README.md
> add storybook

- client/src/app/components/Shared/Documents/documents.scss
> Hide description when pebl is rendered in list mode

- client/src/app/components/App/Modal/ShareModal/ShareModal.jsx
> Show View Only as selected for student

- client/src/app/components/App/Modal/ShareModal/ShareModal.jsx
> Show view only option selected for student

- client/src/app/components/App/Shared/EditorComponents/CodeEditor/CodeEditor.jsx
> fix #873 - Processing ssketch syntax highlight

- client/src/app/components/App/Shared/EditorComponents/EditorFiles/EditorFiles.jsx
- client/src/app/components/App/Shared/FileUpload/FileUpload.jsx
- client/src/app/constants/widgetConstants.js
> fix #874 - allow loadJSON and loadStrings in p5

- client/src/app/action/classroom.js
- server/package.json
- server/scripts/export_creds.sh
- server/scripts/run_with_credstash.sh
- server/src/service/mailSenderService.js
> Add api key to be used for sending emails through sendgrid

- client/src/app/action/classroom.js
- client/src/app/components/ClassView/Assignments/CreateAssignmentModal/CreateAssignmentModal.jsx
- client/src/app/components/ClassViewStudent/AssignmentCard/AssignmentCard.jsx
- client/src/app/components/ClassViewStudent/AssignmentCard/assignmentCard.scss
> 881 start assignment flow refinment

- client/src/app/components/ClassView/Assignments/EditAssignmentModal/EditAssignmentModal.jsx
- client/src/app/components/ClassView/Assignments/EditAssignmentModal/editAssignmentModal.scss
> Fix edit assignment add link integration

- server/devops/ecosystem.config.js
> Add timestamp to server logs

- server/src/controllers/authController.js
> Read email from user in scope instead of upper scope

- client/src/app/components/Shared/Documents/DocumentsView/Pages/pages.scss
> Remove border from pebl title when in rows view

- client/src/app/components/App/Canvas/EditorContainer/editorContainer.scss
- client/src/app/components/App/Shared/EditorComponents/EditorViews/SplitEditorContainer.jsx
- client/src/app/components/App/Shared/EditorComponents/EditorViews/TabbedEditorContainer.jsx
> Fix split editor horizontal pane initial size issue

- client/src/app/components/App/Shared/EditorComponents/EditorViews/SplitEditorContainer.jsx
- client/src/app/components/App/Shared/EditorComponents/EditorViews/TabbedEditorContainer.jsx
- client/src/app/components/App/Shared/EditorComponents/PythonRepl/PythonRepl.jsx
> Do not render console and output components when code is not playing

- requirements.txt
- server/devops/ansible/inventories/cross_env_vars.yml
- server/devops/ansible/inventories/production/ec2.py
- server/devops/ansible/inventories/staging/ec2.py
- server/devops/ansible/roles/deploy_webserver/tasks/main.yml
- server/devops/ansible/roles/provision_webserver/tasks/main.yml
> Python upgrade

- client/src/app/components/App/Shared/EditorComponents/PythonRepl/PythonRepl.jsx
- server/src/service/pageService.js
> Skulpt alert fix

- .vscode/tasks.json
- client/src/app/components/App/Shared/GoogleButton/GoogleLoginButton.jsx
- client/src/app/components/App/Shared/GoogleButton/GoogleSignupButton.jsx
- server/scripts/export_creds.sh
- server/src/controllers/authController.js
> Fix login from classroom route
